compile:
	gcc findtopk.c -o findtopk
	gcc enbuyugubul.c -o enbuyugubul
	gcc findtopk_mqueue.c -o findtopk_mqueue -lrt
	gcc enbuyugubul_mqueue.c -o enbuyugubul_mqueue -lrt
	gcc findtopk_thread.c -o findtopk_thread -lpthread
